// Security and performance improvements
// ============================================================================

[build]
  command = "npm run build" # FIXED: Run full build, not just client
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# ADDED: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# ADDED: Performance headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API redirects (existing)
[[redirects]]
  force = true
  from = "/api/check-verm-balance"
  status = 200
  to = "/.netlify/functions/check-verm-balance"

[[redirects]]
  force = true
  from = "/api/platform/analytics"
  status = 200
  to = "/.netlify/functions/platform-analytics"

[[redirects]]
  force = true
  from = "/api/user/profile"
  status = 200
  to = "/.netlify/functions/user-profile"

[[redirects]]
  force = true
  from = "/api/user/profile/update"
  status = 200
  to = "/.netlify/functions/user-profile-update"

[[redirects]]
  force = true
  from = "/api/track-scan"
  status = 200
  to = "/.netlify/functions/track-scan"

[[redirects]]
  force = true
  from = "/api/ip-scan-tracking"
  status = 200
  to = "/.netlify/functions/ip-scan-tracking"

[[redirects]]
  force = true
  from = "/api/scan-history"
  status = 200
  to = "/.netlify/functions/scan-history"

[[redirects]]
  force = true
  from = "/api/verm-price"
  status = 200
  to = "/.netlify/functions/verm-price"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ============================================================================
// 6. UPDATED: tsconfig.json - Strict mode enabled
// ============================================================================

{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,

    /* UPDATED: Strict linting - CRITICAL for production */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "exactOptionalPropertyTypes": true,

    /* Path mapping */
    "baseUrl": ".",
    "paths": {
      "@/*": ["./client/*"],
      "@shared/*": ["./shared/*"]
    }
  },
  "include": [
    "client/**/*",
    "server/**/*",
    "shared/**/*",
    "vite.config.ts",
    "vite.config.server.ts"
  ],
  "exclude": ["node_modules", "dist"]
}
