# netlify.toml
[build]
  command = "npm run build:client"   # or your actual client build
  publish = "dist/spa"               # must contain index.html after build

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]  # if your api function uses express

# Route all /api/* to the ONE function named 'api'
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
